VetApp/Areas/Admin/Controllers/ManageUsersController.cs
namespace VetApp.Areas.Admin.Controllers
{
	using Microsoft.AspNetCore.Identity;
	using Microsoft.AspNetCore.Mvc;

	using VetApp.Data.Models;

	public class ManageUsersController : AdminBaseController
	{
		private readonly UserManager<ApplicationUser> userManager;

		public ManageUsersController(
			UserManager<ApplicationUser> userManager)
		{
			this.userManager = userManager;
		}
		public IActionResult Index()
		{
			return View();
		}

		[HttpGet]
		public IActionResult All()
		{
			var model = userManager.Users.ToArray();
			return View(model);
		}

		[HttpPost]
		public async Task<IActionResult> DeleteUser(string userId)
		{
			var user = await userManager.FindByIdAsync(userId);

			if (user == null)
			{
				TempData["error"] = "User cannot be found";
				return RedirectToAction("All");
			}

			var result = await userManager.DeleteAsync(user);

			if (result.Succeeded)
			{
				TempData["success"] = "Successfully delete user";
				return RedirectToAction("All");
			}

			foreach (var error in result.Errors)
			{
				ModelState.AddModelError(string.Empty, error.Description);
			}

			return RedirectToAction("All");
		}
	}
}

VetApp/Areas/Admin/Views/ManageUsers/All.cshtml
@model IEnumerable<ApplicationUser>

@{
	ViewData["Title"] = "All Users";
}

<partial name="_NotificationPartial" />

<div class="row d-flex align-items-center justify-content-center mt-4">
	<div class="col-md-6 card p-3">
		<div class="row mb-2">
			<div class="col">
				<a class="btn btn-primary @(Model.Any() == false ? "d-none" : "")" asp-area="" asp-controller="Account" asp-action="Register">Add User</a>
			</div>
			<div class="col">
				<h3 class="card-title text-center text-info">@ViewData["Title"]</h3>
			</div>
			<div class="col"></div>
		</div>
		@if (Model.Any())
		{
			foreach (var user in Model)
			{
				<div class="card mb-2">
					<div class="card-header">Role Id : @user.Id</div>
					<div class="card-body">
						<h5 class="card-title">@user.UserName</h5>
					</div>
					<div class="card-footer">
						<form asp-action="DeleteUser" asp-area="Admin" method="post" asp-controller="ManageUsers" asp-route-userId="@user.Id">
							<button type="submit" class="btn btn-danger">Delete</button>
						</form>
					</div>
				</div>
			}
		}
		else
		{
			<div class="card">
				<div class="card-header">
					No users created yet
				</div>
				<div class="card-body">
					<h5 class="card-title">Use the button below to create a user</h5>
				</div>
				<a class="btn btn-primary col-2 m-2 flex-end" asp-area="Admin" asp-action="AddUser" asp-controller="ManageUsers">Add User</a>
			</div>
		}
	</div>
</div>