VetApp/Areas/Admin/Models/AddRoleViewModel.cs
namespace VetApp.Areas.Admin.Models
{
	using System.ComponentModel.DataAnnotations;
	using static VetApp.Web.Common.ViewModelValidationConstants.AddRoleViewModelConstants;

	public class AddRoleViewModel
	{
		[Required]
		[Display(Name = "Role name")]
		[StringLength(NameMaxLength, MinimumLength = NameMinLength)]
		public string RoleName { get; set; } = null!;
    }
}

VetApp/Areas/Admin/Models/EditRoleViewModel.cs
namespace VetApp.Areas.Admin.Models
{
	using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public class EditRoleViewModel
	{
		public EditRoleViewModel()
		{
			this.Users = new List<string>();
		}

		public string Id { get; set; } = null!;

		[Required]
		[Display(Name = "Role name")]
		public string RoleName { get; set; } = null!;

		public List<string> Users { get; set; }
	}
}

VetApp/Areas/Admin/Controllers/ManageRolesController.cs
namespace VetApp.Areas.Admin.Controllers
{
	using Microsoft.AspNetCore.Identity;
	using Microsoft.AspNetCore.Mvc;
	using Microsoft.EntityFrameworkCore;

	using VetApp.Areas.Admin.Models;
	using VetApp.Data.Models;
	using VetApp.Extensions;

	public class ManageRolesController : AdminBaseController
	{
		private readonly RoleManager<IdentityRole<Guid>> roleManager;
		private readonly UserManager<ApplicationUser> userManager;

		public ManageRolesController(
			RoleManager<IdentityRole<Guid>> roleManager,
			UserManager<ApplicationUser> userManager)
		{
			this.roleManager = roleManager;
			this.userManager = userManager;
		}

		[HttpGet]
		public IActionResult All()
		{
			var model = roleManager.Roles.ToArray();
			ViewBag.UserId = User.Id();
			return View(model);
		}

		[HttpGet]
		public IActionResult AddRole()
		{
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> AddRole(AddRoleViewModel model)
		{
			if (ModelState.IsValid)
			{
				if (await roleManager.RoleExistsAsync(model.RoleName) == false)
				{
					IdentityRole<Guid> role = new()
					{
						Name = model.RoleName
					};

					IdentityResult result = await roleManager.CreateAsync(role);

					if (result.Succeeded)
					{
						return RedirectToAction("All");
					}

					foreach (IdentityError error in result.Errors)
					{
						ModelState.AddModelError(string.Empty, error.Description);
					}
				}
			}

			return View(model);
		}

		[HttpGet]
		public async Task<IActionResult> EditRole(string roleId)
		{
			var role = await roleManager.Roles.FirstOrDefaultAsync(r => r.Id.ToString() == roleId);

			if (role == null)
			{
				TempData["error"] = "Role does not exist.";
				return RedirectToAction("Index", "Home");
			}

			var model = new EditRoleViewModel()
			{
				Id = role.Id.ToString(),
				RoleName = role.Name
			};

			var users = userManager.Users.ToList();

			foreach (var user in users)
			{
				if (await this.userManager.IsInRoleAsync(user, role.Name))
				{
					model.Users.Add(user.UserName);
				}
			}

			return View(model);
		}

		[HttpPost]
		public async Task<IActionResult> EditRole(EditRoleViewModel model)
		{
			var role = await roleManager.Roles.FirstOrDefaultAsync(r => r.Id.ToString() == model.Id);

			if (role == null)
			{
				TempData["error"] = "Role does not exist.";
				return RedirectToAction("All");
			}
			else
			{
				role.Name = model.RoleName;
				var result = await this.roleManager.UpdateAsync(role);

				if (result.Succeeded)
				{
					return RedirectToAction("All");
				}

				foreach (var error in result.Errors)
				{
					ModelState.AddModelError(string.Empty, error.Description);
				}
			}

			return View(model);
		}

		[HttpGet]
		public async Task<IActionResult> EditUsersInRole(string roleId)
		{
			ViewBag.RoleId = roleId;

			IdentityRole<Guid> role = await roleManager.FindByIdAsync(roleId);

			if (role == null)
			{
				TempData["error"] = "Role does not exist.";
				return RedirectToAction("All");
			}

			List<UserRoleViewModel> model = new();

			List<ApplicationUser> users = await userManager.Users.ToListAsync();

			foreach (var user in users)
			{
				bool isUserInRole = await userManager.IsInRoleAsync(user, role.Name);

				model.Add(new UserRoleViewModel()
				{
					UserId = user.Id.ToString(),
					UserName = user.UserName,
					IsSelected = isUserInRole
				});
			}

			return View(model);
		}

		[HttpPost]
		public async Task<IActionResult> EditUsersInRole(List<UserRoleViewModel> model, string roleId)
		{
			IdentityRole<Guid> role = await roleManager.FindByIdAsync(roleId);

			if (role == null)
			{
				TempData["error"] = "Role does not exist.";
				return RedirectToAction("All");
			}

			foreach (var userRole in model)
			{
				ApplicationUser user = await userManager.FindByIdAsync(userRole.UserId);

				if (user == null)
				{
					continue;
				}

				bool isInRole = await userManager.IsInRoleAsync(user, role.Name);

				if (userRole.IsSelected && !isInRole)
				{
					await userManager.AddToRoleAsync(user, role.Name);
				}
				else if (!userRole.IsSelected && isInRole)
				{
					await userManager.RemoveFromRoleAsync(user, role.Name);
				}
			}

			return RedirectToAction("EditRole", new { roleId });
		}

		[HttpPost]
		public async Task<IActionResult> DeleteRole(string roleId)
		{
			var role = await roleManager.FindByIdAsync(roleId);

			if (role == null)
			{
				TempData["error"] = "Role cannot be found";
				return RedirectToAction("All");
			}

			var result = await roleManager.DeleteAsync(role);

			if (result.Succeeded)
			{
				TempData["success"] = "Successfully delete role";
				return RedirectToAction("All");
			}

			foreach (var error in result.Errors)
			{
				ModelState.AddModelError(string.Empty, error.Description);
			}

			return RedirectToAction("All");
		}

	}
}

VetApp/Areas/Admin/Views/ManageRoles/AddRole.cshtml
@model AddRoleViewModel
@{
	ViewData["Title"] = "Add New Role";
}


<div class="row d-flex align-items-center justify-content-center mt-4">
	<div class="col-6 col-md-4 col-lg-3 card p-3">
		<h2 class="card-title text-center text-info">@ViewData["Title"]</h2>
		<form asp-area="Admin" asp-action="AddRole" asp-controller="ManageRoles" method="post">
			<div class="card-body p-0">
				<div asp-validation-summary="All"></div>

				<div class="mb-2">
					<label asp-for="RoleName" class="control-label"></label>
					<input asp-for="RoleName" class="form-control" placeholder="...">
					<span asp-validation-for="RoleName" class="text-danger"></span>
				</div>
			</div>
			<input type="submit" value="Add Role" class="btn btn-primary btn-sm" />
			<a class="btn btn-primary btn-sm" asp-area="Admin" asp-action="All" asp-controller="ManageRoles">Cancle</a>
		</form>
	</div>
</div>

@section Scripts {
	<partial name="_ValidationScriptsPartial" />
}

VetApp/Areas/Admin/Views/ManageRoles/All.cshtml
@model IEnumerable<IdentityRole<Guid>>

@{
	ViewData["Title"] = "All Roles";
	var userId = ViewBag.UserId;
}

<partial name="_NotificationPartial" />

<div class="row d-flex align-items-center justify-content-center mt-4">
	<div class="col-md-6 card p-3">
		<div class="row mb-2">
			<div class="col">
				<a class="btn btn-primary @(Model.Any() == false ? "d-none" : "")" asp-area="Admin" asp-controller="ManageRoles" asp-action="AddRole">Add Role</a>
			</div>
			<div class="col">
				<h3 class="card-title text-center text-info">@ViewData["Title"]</h3>
			</div>
			<div class="col"></div>
		</div>
		@if (Model.Any())
		{
			foreach (var role in Model)
			{
				<div class="card mb-2">
					<div class="card-header">Role Id : @role.Id</div>
					<div class="card-body">
						<h5 class="card-title">@role.Name</h5>
					</div>
					<div class="card-footer">
						<form asp-action="DeleteRole" asp-area="Admin" method="post" asp-controller="ManageRoles" asp-route-roleId="@role.Id">
							<a class="btn btn-primary"
							   asp-area="Admin" asp-action="EditRole"
							   asp-controller="ManageRoles" asp-route-roleId="@role.Id">
								Edit
							</a>
							<button type="submit" class="btn btn-danger">Delete</button>
						</form>
					</div>
				</div>
			}
		}
		else
		{
			<div class="card">
				<div class="card-header">
					No roles created yet
				</div>
				<div class="card-body">
					<h5 class="card-title">Use the button below to create a role</h5>
				</div>
				<a class="btn btn-primary col-2 m-2 flex-end" asp-area="Admin" asp-action="AddRole" asp-controller="ManageRoles">Add Role</a>
			</div>
		}
	</div>
</div>

VetApp/Areas/Admin/Views/ManageRoles/EditRole.cshtml
@model EditRoleViewModel

@{
	ViewData["Title"] = "Edit Role";
}

<div class="row d-flex align-items-center justify-content-center mt-4">
	<div class="col-md-6 card p-3">
		<h2 class="card-title text-center text-info">@ViewData["Title"]</h2>
		<form asp-area="Admin" asp-action="EditRole" asp-controller="ManageRoles" method="post">
			<div class="card-body p-0">

				<div class="row mb-2">
					<label asp-for="Id" class="col-2 col-form-label"></label>
					<div class="col-10">
						<input asp-for="Id" disabled class="form-control">
						<input asp-for="Id" hidden class="form-control">
					</div>
				</div>

				<div class="row mb-2">
					<label asp-for="RoleName" class="col-sm-2 col-form-label"></label>
					<div class="col-sm-10">
						<input asp-for="RoleName" class="form-control">
						<span asp-validation-for="RoleName" class="text-danger"></span>
					</div>
				</div>

				<div asp-validation-summary="ModelOnly"></div>

				<div class="form-group row mb-2">
					<div class="col-sm-10">
						<input type="submit" value="Save" class="btn btn-primary btn-sm" />
						<a class="btn btn-primary btn-sm" asp-area="Admin" asp-action="All" asp-controller="ManageRoles">Cancle</a>
					</div>
				</div>
			</div>

			<div class="card">
				<div class="card-header">
					<h3 class="card-title">Users in this role</h3>
				</div>
				<div class="card-body">
					@if (Model.Users.Any())
					{
						foreach (var user in Model.Users)
						{
							<h5 class="card-title">@user</h5>
						}
					}
					else
					{
						<h5 class="card-title">None at the moment</h5>
					}
				</div>
				<div class="card-footer">
					<a class="btn btn-primary" asp-area="Admin" asp-controller="ManageRoles" asp-action="EditUsersInRole"
						asp-route-roleId="@Model.Id">Add or remove users</a>
				</div>
			</div>

		</form>
	</div>
</div>

@section Scripts {
	<partial name="_ValidationScriptsPartial" />
}

VetApp/Areas/Admin/Views/ManageRoles/EditUsersInRole.cshtml
@model List<UserRoleViewModel>

@{
	ViewData["Title"] = "Edit users in role";
	string roleId = ViewBag.RoleId;
}

<div class="row d-flex align-items-center justify-content-center mt-4">
	<div class="col-md-6 card p-3">
		<form method="post">

			<h2 class="card-title text-center text-info">Add or remove users from this role</h2>

			<div class="card-body">
				@for (int i = 0; i < Model.Count(); i++)
				{
					<div class="form-check m-1">
						<input type="hidden" asp-for="@Model[i].UserId" />
						<input type="hidden" asp-for="@Model[i].UserName" />

						<input asp-for="@Model[i].IsSelected" class="form-check-input" />
						<label asp-for="@Model[i].UserName" class="form-check-label">
							@Model[i].UserName
						</label>
					</div>
				}
			</div>

			<div class="card-footer">
				<input type="submit" value="Save" class="btn btn-primary btn-sm" />
				<a class="btn btn-primary btn-sm" asp-area="Admin" asp-action="EditRole"
				   asp-controller="ManageRoles" asp-route-roleId="@roleId">Cancle</a>
			</div>

		</form>
	</div>
</div>