VetApp/Controllers/ExaminationController.cs
namespace VetApp.Controllers
{
	using Microsoft.AspNetCore.Mvc;

	using VetApp.Extensions;
	using VetApp.Services.Interfaces;
	using VetApp.Services.Models.Examination;
	using VetApp.Web.Common.Helpers;
	using VetApp.Web.ViewModels.Examination;
	using VetApp.Web.ViewModels.Patient;
	using VetApp.Web.ViewModels.Status;

	public class ExaminationController : BaseController
	{
		private readonly IExaminationService examinationService;
		private readonly IPatientService patientService;
		private readonly IStatusService statusService;
		private readonly IWebHostEnvironment webHostEnvironment;
		private readonly IAccountService accountService;

		public ExaminationController(IExaminationService examinationService,
			IPatientService patientService, IStatusService statusService,
			IWebHostEnvironment webHostEnvironment, IAccountService accountService)
		{
			this.examinationService = examinationService;
			this.patientService = patientService;
			this.statusService = statusService;
			this.webHostEnvironment = webHostEnvironment;
			this.accountService = accountService;
		}

		[HttpGet]
		public async Task<IActionResult> Add(string patientId)
		{
			if (string.IsNullOrEmpty(patientId))
			{
				TempData["error"] = "Patient Id is required.";
				return RedirectToAction("All", "Patient");
			}

			try
			{
				PatientViewModel patient = await patientService.GetPatientByIdAsync(patientId);
				IEnumerable<StatusViewModel> statuses = await statusService.AllStatusesAsync();
				ViewBag.DoctorFullName =
					await accountService.GetUserFullNameByUsernameAsync(User.Identity?.Name!);

				ExaminationFormModel examination = new()
				{
					DoctorId = User.Id(),
				};

				AddAndEditExaminationViewModel model = new()
				{
					Patient = patient,
					Examination = examination
				};

				return View(model);
			}
			catch (InvalidOperationException)
			{
				TempData["error"] = "Patient does not exist.";
				return RedirectToAction("All", "Patient");
			}
			catch (Exception ex)
			{
				TempData["error"] = ex.Message;
				return RedirectToAction("Index", "Home");
			}
		}

		[HttpPost]
		public async Task<IActionResult> Add(AddAndEditExaminationViewModel model, string patientId)
		{
			if (string.IsNullOrEmpty(patientId))
			{
				TempData["error"] = "Patient Id is required.";
				return RedirectToAction("All", "Patient");
			}

			try
			{
				PatientViewModel patient = await patientService.GetPatientByIdAsync(patientId);

				if (!ModelState.IsValid)
				{
					model.Patient = patient;
					model.Examination = new ExaminationFormModel()
					{
						DoctorId = User.Id(),
					};

					return View(model);
				}

				await this.examinationService.AddAsync(model.Examination, patientId, User.Id());
				TempData["success"] = "Examination was added successfully.";

				return RedirectToAction("Details", "Patient", new { patientId });
			}
			catch (InvalidOperationException)
			{
				TempData["error"] = "Patient does not exist.";
				return RedirectToAction("All", "Patient");
			}
			catch (Exception ex)
			{
				TempData["error"] = ex.Message;
				return RedirectToAction("Index", "Home");
			}
		}

		[HttpGet]
		public async Task<IActionResult> All(AllExaminationsQueryModel queryModel)
		{
			try
			{
				AllExaminationsOrderedAndPagedServiceModel serviceModel =
					await examinationService.GetAllExaminationsAsync(queryModel);

				queryModel.Examinations = serviceModel.Examinations;

				Pager pager = new(queryModel.CurrentPage, queryModel.ExaminationsPerPage, serviceModel.TotalItems);

				ViewBag.Pager = pager;

				return View(queryModel);
			}
			catch (Exception ex)
			{
				TempData["error"] = ex.Message;
				return RedirectToAction("Index", "Home");
			}
		}

		[HttpGet]
		public async Task<IActionResult> Edit(string examinationId, string patientId)
		{
			if (string.IsNullOrEmpty(examinationId))
			{
				TempData["error"] = "Examination Id is required.";
				return RedirectToAction("All");
			}

			if (string.IsNullOrEmpty(patientId))
			{
				TempData["error"] = "Patient Id is required.";
				return RedirectToAction("All", "Patient");
			}

			try
			{
				if (!await this.patientService.PatientExistsAsync(patientId))
				{
					TempData["error"] = "Patient does not exist.";
					return RedirectToAction("All", "Patient");
				}

				PatientViewModel patient = await patientService.GetPatientByIdAsync(patientId);

				if (!await this.examinationService.ExaminationExistsAsync(examinationId))
				{
					TempData["error"] = "Examination does not exist.";
					return RedirectToAction("All");
				}

				ExaminationFormModel examination =
					await examinationService.GetExaminationByIdAsync(examinationId);
				examination.Statuses = await statusService.AllStatusesAsync();

				ViewBag.ExaminationId = examinationId;
				ViewBag.DoctorFullName =
						await accountService.GetUserFullNameByUsernameAsync(User.Identity?.Name!);

				AddAndEditExaminationViewModel model = new()
				{
					Patient = patient,
					Examination = examination,
				};

				return View(model);
			}
			catch (Exception ex)
			{
				TempData["error"] = ex.Message;
				return RedirectToAction("Index", "Home");
			}

		}

		[HttpPost]
		public async Task<IActionResult> Edit(AddAndEditExaminationViewModel model, string examinationId, string patientId)
		{
			if (string.IsNullOrEmpty(examinationId))
			{
				TempData["error"] = "Examination Id is required.";
				return RedirectToAction("All");
			}

			if (string.IsNullOrEmpty(patientId))
			{
				TempData["error"] = "Patient Id is required.";
				return RedirectToAction("All", "Patient");
			}

			try
			{
				PatientViewModel patient =
					await patientService.GetPatientByIdAsync(patientId);

				if (!await this.examinationService.ExaminationExistsAsync(examinationId))
				{
					TempData["error"] = "Examination does not exist.";
					return RedirectToAction("All");
				}

				if (!ModelState.IsValid)
				{
					model.Patient = patient;
					model.Examination.Statuses =
						await statusService.AllStatusesAsync();

					return View(model);
				}

				await examinationService.EditExaminationAsync(model.Examination, examinationId);
				TempData["success"] = "Examination was edited successfully.";

				return RedirectToAction("Details", "Patient", new { patientId });
			}
			catch (InvalidOperationException)
			{
				TempData["error"] = "Patient does not exist.";
				return RedirectToAction("All", "Patient");
			}
			catch (Exception ex)
			{
				TempData["error"] = ex.Message;
				return RedirectToAction("Index", "Home");
			}
		}

		[HttpGet]
		public async Task<IActionResult> Dashboard()
		{
			try
			{
				var model = await examinationService.GetExaminationsGroupedByStatus();

				return View(model);
			}
			catch (Exception ex)
			{
				TempData["error"] = ex.Message;
				return RedirectToAction("Index", "Home");
			}
		}

		[HttpGet]
		public async Task<IActionResult> Details(string examinationId)
		{
			if (string.IsNullOrEmpty(examinationId))
			{
				TempData["error"] = "Examination Id is required.";
				return RedirectToAction("All");
			}

			try
			{
				ExaminationDetailsViewModel model =
					await examinationService.GetExaminationDetailsByIdAsync(examinationId);

				return View(model);
			}
			catch (InvalidOperationException)
			{
				TempData["error"] = "Examination does not exist.";
				return RedirectToAction("All");
			}
			catch (Exception ex)
			{
				TempData["error"] = ex.Message;
				return RedirectToAction("Index", "Home");
			}
		}

		[HttpGet]
		public async Task<IActionResult> Delete(string examinationId)
		{
			if (string.IsNullOrEmpty(examinationId))
			{
				TempData["error"] = "Examination Id is required.";
				return RedirectToAction("All");
			}

			try
			{
				PreDeleteDetailsViewModel model =
				await this.examinationService.GetExaminationForDeleteByIdAsync(examinationId);

				if (model.StatusName == "Done")
				{
					TempData["error"] = "Can not delete examinations with status 'Done'.";
					return RedirectToAction("All");
				}

				return View(model);
			}
			catch (InvalidOperationException)
			{
				TempData["error"] = "Examination does not exist.";
				return RedirectToAction("All");
			}
			catch (Exception ex)
			{
				TempData["error"] = ex.Message;
				return RedirectToAction("Index", "Home");
			}
		}

		[HttpPost]
		public async Task<IActionResult> Delete(string examinationId, PreDeleteDetailsViewModel model)
		{
			try
			{
				await this.examinationService.DeleteExaminationByIdAsync(examinationId);
				TempData["success"] = "The examination was successfully deleted.";
				return RedirectToAction("All");
			}
			catch (Exception ex)
			{
				TempData["error"] = ex.Message;
				return RedirectToAction("Index", "Home");
			}
		}
	}
}

VetApp/Views/Shared/_ExaminationPartialVM.cshtml
@model AddExaminationFM

@{
    ViewData["Title"] = "All Patients";
}

<dl class="row">
	<dt class="col-sm-4">Name:</dt>
	<dd class="col-sm-8">@Model.Patient.Name</dd>

	<dt class="col-sm-4">Type:</dt>
	<dd class="col-sm-8">@Model.Patient.Type</dd>

	<dt class="col-sm-4">Birthdate:</dt>
	<dd class="col-sm-8">@Model.Patient.BirthDate</dd>

	<dt class="col-sm-4">Gender:</dt>
	<dd class="col-sm-8">@Model.Patient.Gender</dd>

	<dt class="col-sm-4">Neutered:</dt>
	<dd class="col-sm-8">@Model.Patient.Neutered</dd>

	<dt class="col-sm-4">Microchip:</dt>
	<dd class="col-sm-8">@Model.Patient.Microchip</dd>

	<dt class="col-sm-4">Chronic illnesses:</dt>
	<dd class="col-sm-8">@Model.Patient.ChronicIllnesses</dd>

	<dt class="col-sm-4">Characteristics:</dt>
	<dd class="col-sm-8">@Model.Patient.Characteristics</dd>
</dl>

VetApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - VetTrackingSystem</title>
	<link rel="stylesheet" href="~/css/bootstrap.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/VetApp.styles.css" asp-append-version="true" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" asp-append-version="true" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
			<div class="container-fluid">
				<a class="navbar-brand" asp-controller="Home" asp-action="Index">VetTrackingSystem</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarColor01">
					@await Component.InvokeAsync(nameof(MainMenuComponent))
					<partial name="_LoginPartial" />
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; @DateTime.UtcNow.Year - VetApp
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

VetApp/Views/Shared/_NotificationPartial.cshtml
@if (TempData["success"] != null)
{
	<script src="~/lib/jquery/dist/jquery.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
	<script type="text/javascript">
		toastr.success('@TempData["success"]');
	</script>
}
else if (TempData["warning"] != null)
{
	<script src="~/lib/jquery/dist/jquery.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
	<script type="text/javascript">
		toastr.warning('@TempData["warning"]');
	</script>
}
else if (TempData["error"] != null)
{
	<script src="~/lib/jquery/dist/jquery.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
	<script type="text/javascript">
		toastr.error('@TempData["error"]');
	</script>
}

VetApp/Views/Shared/_OwnerAllPartial.cshtml
@{
	ViewData["Title"] = "All Owners";
}

<div class="col mb-2">
	<div class="card border-secondary" style="max-width: 25rem; margin: 10px 0px">
		<h4 class="card-header">@Model.Name</h4>
		<div class="card-body">
			<dl class="row">
				<dt class="col-sm-5 card-title">Address:</dt>
				<dd class="col-sm-5 card-text">@Model.Address</dd>

				<dt class="col-sm-5 card-title">PhoneNumber:</dt>
				<dd class="col-sm-5 card-text">@Model.PhoneNumber</dd>

				@if (Model.Email != null)
				{
					<dt class="col-sm-5 card-title">Email:</dt>
					<dd class="col-sm-5 card-text">@Model.Email</dd>
				}
			</dl>
			<a class="btn btn-outline-primary text-white" asp-controller="Patient" asp-action="AddPet" asp-route-ownerId="@Model.Id">Add Pet</a>
			<a class="btn btn-outline-info text-white" asp-controller="Owner" asp-action="Details" asp-route-ownerId="@Model.Id">Details</a>
			<a class="btn btn-outline-warning text-white" asp-controller="Owner" asp-action="Edit" asp-route-ownerId="@Model.Id">Edit</a>
		</div>
	</div>
</div>

VetApp/Views/Shared/_PaginationBottomBarPartial.cshtml
<div class="row justify-content-between">

	<div class="col-4">
		<p class=" m-0">
			Showing @Model.StartRecord to @Model.EndRecord of @Model.TotalItems Rows
		</p>
	</div>

	<div class="col-4">
		<p>
			<span class="float-end align-items-center">
				Showing @Model.CurrentPage / @Model.TotalPages
			</span>
		</p>
	</div>

</div>

VetApp/Views/Shared/_PatientAllPartial.cshtml
@{
	ViewData["Title"] = "All Patients";
}

<div class="col mb-4">
	<div class="card border-secondary" >
		<h4 class="card-header">@Model.Name</h4>
		<div class="card-body">
			<dl class="row">
				<dt class="col-6 card-title">Type:</dt>
				<dd class="col-6 card-text">@Model.Type</dd>

				<dt class="col-6 card-title">Gender:</dt>
				<dd class="col-6 card-text">@Model.Gender</dd>

				<dt class="col-6 card-title">Neutered:</dt>
				<dd class="col-6 card-text">@Model.Neutered</dd>

				<dt class="col-6 card-title">Owner Name:</dt>
				<dd class="col-6 card-text">@Model.OwnerName</dd>
			</dl>
			<a class="btn btn-outline-primary text-white" asp-controller="Examination" asp-action="Add" asp-route-patientId="@Model.Id">Add Examination</a>
			<a class="btn btn-outline-info text-white" asp-controller="Patient" asp-action="Details" asp-route-patientId="@Model.Id">Details</a>
			<a class="btn btn-outline-warning text-white" asp-controller="Patient" asp-action="Edit" asp-route-patientId="@Model.Id">Edit</a>
		</div>
	</div>
</div>

VetApp/Views/Shared/_PatientAllPartialView.cshtml
@{
	ViewData["Title"] = "All Patients";
}

@foreach (var patient in Model)
{
	<tr class="table-dark">
		<td>
			@patient.Name
		</td>
		<td>
			@patient.Type
		</td>
		<td>
			@if (patient.BirthDate != null)
			{
				@patient.BirthDate.ToString("dd.MM.yyyy")
			}
		</td>
		<td>
			@patient.Gender
		</td>
		<td>
			@patient.Neutered
		</td>
		<td>
			<a class="btn btn-outline-primary text-white" asp-controller="Examination" asp-action="Add" asp-route-patientId="@patient.Id">Add Examination</a>
		</td>
		<td>
			<a class="btn btn-outline-warning text-white" asp-controller="Patient" asp-action="Edit" asp-route-id="@patient.Id">Edit</a>
		</td>
		<td>
			<a class="btn btn-outline-info text-white" asp-controller="Patient" asp-action="Details" asp-route-id="@patient.Id">Details</a>
		</td>
	</tr>
}

VetApp/Views/Shared/_PatientDetailsPartial.cshtml
@{
	ViewData["Title"] = "Patient Details";
}

<div class="card border-secondary mb-3" style="margin: 10px 0px">
	<h4 class="card-header">@Model.Name</h4>
	<div class="card-body">
		<dl class="row">
			<dt class="col-5 card-title">Type:</dt>
			<dd class="col-7 card-text">@Model.Type</dd>

			<dt class="col-5 card-title">Gender:</dt>
			<dd class="col-7 card-text">@Model.Gender</dd>

			<dt class="col-5 card-title">Neutered:</dt>
			<dd class="col-7 card-text">@Model.Neutered</dd>

			<dt class="col-5 card-title">Owner Name:</dt>
			<dd class="col-7 card-text">@Model.OwnerName</dd>

			<dt class="col-5 card-title">BirthDate:</dt>
			<dd class="col-7 card-text">
				@if (Model.BirthDate != null)
				{
					@Model.BirthDate.ToString("yyyy-MM-dd");
				}
			</dd>

			<dt class="col-5 card-title">Microchip:</dt>
			<dd class="col-7 card-text">@Model.Microchip</dd>

			<dt class="col-5 card-title">Chronic Illnesses:</dt>
			<dd class="col-7 card-text">@Model.ChronicIllnesses</dd>

			<dt class="col-5 card-title">Characteristics:</dt>
			<dd class="col-7 card-text">@Model.Characteristics</dd>
		</dl>

		<a id="addExaminationBtn" class="btn btn-outline-primary text-white" asp-controller="Examination" asp-action="Add" asp-route-patientId="@Model.Id">Add Examination</a>
		<a class="btn btn-outline-warning text-white" asp-controller="Patient" asp-action="Edit" asp-route-patientId="@Model.Id">Edit</a>
	</div>
</div>

<script>
	function getCurrentRoute() {
		let pathArray = window.location.pathname.split('/');
		let controller = pathArray[1];
		let action = pathArray[2];
		return { controller: controller, action: action };
	}

	let currentRoute = getCurrentRoute();

	if (currentRoute.controller.toLowerCase() === "examination" &&
		currentRoute.action.toLowerCase() === "add") {
		document.getElementById("addExaminationBtn").style.display = "none";
	}
</script>

VetApp/Views/Shared/_PatientPartial.cshtml
@{
	ViewData["Title"] = "Patient Details";
}

<div class="card border-secondary mb-3" style="max-width: 25rem; margin: 10px 0px">
	<h4 class="card-header">@Model.Name</h4>
	<div class="card-body">
		<dl class="row">
			<dt class="col-sm-5 card-title">Type:</dt>
			<dd class="col-sm-5 card-text">@Model.Type</dd>

			<dt class="col-sm-5 card-title">BirthDate:</dt>
			<dd class="col-sm-5 card-text">
				@if (Model.BirthDate != null)
				{
					Model.BirthDate.ToString("dd/MM/yyyy");
				}
			</dd>

			<dt class="col-sm-5 card-title">Gender:</dt>
			<dd class="col-sm-5 card-text">@Model.Gender</dd>

			<dt class="col-sm-5 card-title">Neutered:</dt>
			<dd class="col-sm-5 card-text">@Model.Neutered</dd>

			<dt class="col-sm-5 card-title">Microchip:</dt>
			<dd class="col-sm-5 card-text">@Model.Microchip</dd>

			<dt class="col-sm-5 card-title">ChronicIllnesses:</dt>
			<dd class="col-sm-5 card-text">@Model.ChronicIllnesses</dd>

			<dt class="col-sm-5 card-title">Characteristics:</dt>
			<dd class="col-sm-5 card-text">@Model.Characteristics</dd>
		</dl>
	</div>
</div>

VetApp/Views/Shared/_PatientPartialVM.cshtml
@model ICollection<PatientVM>

@{
	ViewData["Title"] = "All Patients";
}

@foreach (var item in Model)
{
	<tr class="table-dark">
		<td>
			@item.Name
		</td>
		<td>
			@item.Type
		</td>
		<td>
			@item.BirthDate
		</td>
		<td>
			@item.Gender
		</td>
		<td>
			@item.Neutered
		</td>
		@* <td>
	<a class="btn btn-warning text-white" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
	</td> *@
		<td>
			<a class="btn btn-info text-white" asp-controller="Examination" asp-action="All" asp-route-patientId="@item.Id">Examinations</a>
		</td>
		<td>
			<a class="btn btn-primary text-white" asp-controller="Patient" asp-action="Details" asp-route-id="@item.Id">Details</a>
		</td>
	</tr>
}

VetApp/Views/Shared/_PatientPartialView.cshtml
@{
    ViewData["Title"] = "All Patients";
}

<div class="card border-secondary mb-3" style="max-width: 25rem; margin: 10px 0px">
	<h4 class="card-header">@Model.Patient.Name</h4>
	<div class="card-body">
		<dl class="row">
			<dt class="col-sm-5 card-title">Type:</dt>
			<dd class="col-sm-5 card-text">@Model.Patient.Type</dd>

			<dt class="col-sm-5 card-title">BirthDate:</dt>
			<dd class="col-sm-5 card-text">@Model.Patient.BirthDate</dd>

			<dt class="col-sm-5 card-title">Gender:</dt>
			<dd class="col-sm-5 card-text">@Model.Patient.Gender</dd>

			<dt class="col-sm-5 card-title">Neutered:</dt>
			<dd class="col-sm-5 card-text">@Model.Patient.Neutered</dd>

			<dt class="col-sm-5 card-title">Microchip:</dt>
			<dd class="col-sm-5 card-text">@Model.Patient.Microchip</dd>

			<dt class="col-sm-5 card-title">ChronicIllnesses:</dt>
			<dd class="col-sm-5 card-text">@Model.Patient.ChronicIllnesses</dd>

			<dt class="col-sm-5 card-title">Characteristics:</dt>
			<dd class="col-sm-5 card-text">@Model.Patient.Characteristics</dd>
		</dl>
	</div>
</div>